### ISSUE TITLE
Rename jsx files .jsx

### ISSUE THREAD

**Issue by braco** [pieterv/react-googlemaps#11]
for example,

```
react-googlemaps/src/ui/components/ReactMap.js
```

is jsx, not js.

This makes building a little hairy, as it's easier to apply a jsx loader to *.jsx. Webpack works this way.

**Comment by kellec** [comment]
If React is included in the module namespace then jsx loader will work on .js files so we shouldn't need the .jsx extension.

**Comment by dempfi** [comment]
+1
