### ISSUE TITLE
draggable map

### ISSUE THREAD

**Issue by mfirry** [pieterv/react-googlemaps#15]
I can't seem to be able to have a draggable map.

This is how I use it: 
```
          <Map
            initialZoom={3}
            center={new GoogleMapsAPI.LatLng(32.770807, -17.038183)}
            width={1000}
            draggable={true}
            height={1000}>
            {markers}
          </Map>
```

**Comment by pieterv** [comment]
Have a look at the examples, https://github.com/pieterv/react-googlemaps/blob/master/examples/markers/app.js#L23-L31, The map is a controlled component like an input in react so you will need to listen for changes and apply them.
