### ISSUE TITLE
`google.maps` global object not found, make sure Google maps in included before react-googlemaps is defined

### ISSUE THREAD

**Issue by dipdipdip84** [pieterv/react-googlemaps#23]
Hi,

I have this error message while I try using the component. Anyone has an idea? 

Thanks for helping ! :)

**Comment by fson** [comment]
@dipdipdip84 You need to load the Google Maps API before the code using react-googlemaps.

See:
https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API

**Comment by pieterv** [comment]
@dipdipdip84 looks like @fson answered this, also check out `examples` dir for more a specific example
