### ISSUE TITLE
react-googlemaps for react 0.13.x

### ISSUE THREAD

**Issue by mfirry** [pieterv/react-googlemaps#29]
Is there any plan to have a version built for react 0.13?

**Comment by wayofspark** [comment]
+1 here

**Comment by uzarubin** [comment]
+1

**Comment by soyjavi** [comment]
+1

**Comment by cyrusbowman** [comment]
+1

**Comment by jacobdubail** [comment]
Is this an abandoned project? Anyone using an alternative?

**Comment by desmondhume** [comment]
+1

**Comment by mfirry** [comment]
I guess we can close this at this point right @pieterv ?

**Comment by mfirry** [comment]
I guess we can close this at this point right @pieterv ?
